<?php
/** @var \AHT\PaymentFee\Block\Cart\Sidebar $block */
?>
<div id="cart-page">
    <div id="block-cart-list" data-bind="scope:'minicart-addons'" class="block">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script>
            maxpriceShipping = <?= /* @escapeNotVerified */ $this->getConfigForShippingBar() ?>;
        </script>
        <script type="text/x-magento-init">
         {
             "#block-cart-list":
                 {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}

        }
     </script>
    </div>
</div>
